server:
    # Escuchar en todas las interfaces para que Pi-hole llegue
    interface: 0.0.0.0
    port: 53
    
    # Permitir consultas de la red interna de Docker
    access-control: 0.0.0.0/0 allow

    # Configuración de seguridad y recursividad
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    
    # IMPORTANTE: Alpine usa esta ruta para las keys de DNSSEC
    auto-trust-anchor-file: "/etc/unbound/root.key"

    # Privacidad
    hide-identity: yes
    hide-version: yes

    # Evitar warning de buffer de envío de sockets
    # Unbound intenta pedir 4MB de buffer de envio de sockets, pero el sistema le otorga menos.
    so-rcvbuf: 0
    so-sndbuf: 0

